### ISSUE TITLE
Can it be used in a formal project?

### ISSUE THREAD

**Issue by xiaoaq** [locus84/LocusReplicationGraph#1]
Like a MMO game?

**Comment by locus84** [comment]
Depends on it's size/scale.
For example, if your game has top-down view, you can scale down entire view distance significantly.
If you want to keep view distance higher enough like PUBG or FortNight, your server might handle less players.

And I think there are three possible choices if you want to make MMOG.

- Use single instance of dedicated server per zone/channel.(with ReplicationGraph)

- Use third party solution integrated with Unreal Networking to make seamless OpenWorld.
    (ex: https://improbable.io/games)

- Implement you're own MMO server.

**Comment by xiaoaq** [comment]
Thanks very much for your answer!
My project has only a few hundred actors, and the map size is not too big. But there is a high demand for number of online players. So，does it suitable for use RepGraph ?
---------------------------------------
Here's a question with plugin using, I‘m set the step 1 to 6 according to "How to install", 
but there is nothing output when I input the console command "LocusRepGraph.PrintRouting"?
So，I'm not sure it worked on my project?

**Comment by locus84** [comment]
That's pretty much suitable case for ReplicationGraph.
--------------------
![image](https://user-images.githubusercontent.com/6591432/53003419-429cd000-3472-11e9-9b9e-80e3876d4c3f.png)
You'll see logs something like this if it's initiated properly.


1. Check DefaultEngine.ini 
[/Script/OnlineSubsystemUtils.IpNetDriver] 
ReplicationDriverClassName=/Game/Blueprints/Online/CustomReplicationGraph.CustomReplicationGraph_C

2. Make sure you restarted/reloaded DefaultEngine.ini.

3. If it still does not works, check again your DefaultEngine.ini and add IPNetDriver explicitly.
[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemUtils.IpNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

4. In case of you're using different NetDriver other than IPNetDriver, for example, you're using SteamNetDriver, you should change ReplicationDriverClassName(case 1 above) like below.
[/Script/OnlineSubsystemUtils.SteamNetDriver] 
ReplicationDriverClassName=/Game/Blueprints/Online/CustomReplicationGraph.CustomReplicationGraph_C

Hope this helps!

**Comment by xiaoaq** [comment]
Thanks very much for your patient answers， Locus!
--------------------------------------------------------
Yeah, It's worked! Output the correct log.
Due to missing the '.CustomReplicationGraph_C' part when I configure 'ReplicationDriverClassName'.
---------------------------------------------------------
How can I clear see the different between using the plugin or not using it in my project?

**Comment by locus84** [comment]
You should spawn large quantity of Spatialize_Dynamic Actors, like 2000~3000 actors or so.
Place them randomly into your map in the server and join with your client.

With ReplicationGraph, relevancy check is based on graph, so cpu usage of the server will be much less than without ReplicationGraph.

If you want to gain more performance with large amount of networked actors, consider using Spatialize_Static, Spatialize_Dormancy setting for static(not moving) or partially dynamic actors.

**Comment by xiaoaq** [comment]
OK, I'll try it and observe the effect.
Thanks again!
